template_project/basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns = [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views

urlpatterns = [
    path('',views.index,name='index'),
    path("admin/", admin.site.urls),
    path('basicapp/',include('basicapp.urls')),
]

template_project/basicapp/models.py
from django.db import models

# Create your models here.

template_project/basicapp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_templates.html') 

template_project/templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous"
    />
    <title>Document</title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar0-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li>
            <a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a>
          </li>
          <li>
            <a class="navbar-link" href="{% url 'basicapp:other' %}">OTHER</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block body_block %} {% endblock %}</div>
  </body>
</html>

template_project/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %} {% load my_extras %} {% block body_block %}

<h1>WELCOME TO INDEX</h1>
<h2>this is index.html hehe</h2>
<h1>{{text|cutout:"hel"}}</h1>
<h1>{{number|add:"99"}}</h1>
{% endblock %}

template_project/templates/basicapp/other.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %} {% load my_extras %} {% block body_block %}

<h1>WELCOME TO OTHER</h1>
<h2>EXAMPLE OF TEMPLATE INHERITANCE</h2>
{% endblock %}

template_project/templates/basicapp/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>
    <br />
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <br />
    <a href="{% url 'index' %}">LINK TO INDEX</a>
    <br />
    <a href="https://www.google.com">GOOGLE</a>
  </body>
</html>